
/* Testbench Configuration */

`define REFINE_SPEC_SYN   1'b1   
`define MASS_TYPE         1'b1   
`define C_N               1'b1  
`define BZERO             1'b0 
`define IS_DALTON         1'b0   
`define IS_PPM            1'b1   
`define FRAG_TYPE         6'b010010
`define PROMPT            1'b0 
`define SEQ_MOD           1'b0  
`define TERM_N            1'b1  
`define TERM_C            1'b0  
`define ISOTOPE_ERR       1'b1  
`define START             1'b1 

`define M_NT              32'h0
`define M_CT              32'h0
`define M_CLEAVE_N        32'h10200d
`define M_CLEAVE_C        32'h1100b34
`define WOE               32'h00280000
`define PARENT_ERR_MINUS  32'h06400000 
`define PARENT_ERR_PLUS   32'h06400000 

`define MOD_LEFT          32'h2a02b46
`define MOD_RIGHT         32'h0
`define MOD_A             32'h0
`define MOD_B             32'h0
`define MOD_C             32'h0
`define MOD_D             32'h0
`define MOD_E             32'h0
`define MOD_F             32'h0
`define MOD_G             32'h0
`define MOD_H             32'h0
`define MOD_I             32'h0
`define MOD_J             32'h0
`define MOD_K             32'h0
`define MOD_L             32'h0
`define MOD_M             32'h0
`define MOD_N             32'h0
`define MOD_O             32'h0
`define MOD_P             32'h0
`define MOD_Q             32'h0
`define MOD_R             32'h0
`define MOD_S             32'h0
`define MOD_T             32'h0
`define MOD_U             32'h0
`define MOD_V             32'h0
`define MOD_W             32'h0
`define MOD_X             32'h0
`define MOD_Y             32'h0
`define MOD_Z             32'h0

`define FULLMOD_LEFT      32'h0
`define FULLMOD_RIGHT     32'h0
/* `define FULLMOD_A         32'h0
`define FULLMOD_B         32'h0
`define FULLMOD_C         32'h0
`define FULLMOD_D         32'h0
`define FULLMOD_E         32'h0
`define FULLMOD_F         32'h0
`define FULLMOD_G         32'h0
`define FULLMOD_H         32'h0
`define FULLMOD_I         32'h0
`define FULLMOD_J         32'h0
`define FULLMOD_K         32'h0
`define FULLMOD_L         32'h0
`define FULLMOD_M         32'h0
`define FULLMOD_N         32'h0
`define FULLMOD_O         32'h0
`define FULLMOD_P         32'h0
`define FULLMOD_Q         32'h0
`define FULLMOD_R         32'h0
`define FULLMOD_S         32'h0
`define FULLMOD_T         32'h0
`define FULLMOD_U         32'h0
`define FULLMOD_V         32'h0
`define FULLMOD_W         32'h0
`define FULLMOD_X         32'h0
`define FULLMOD_Y         32'h0
`define FULLMOD_Z         32'h0

`define PROMPT_A          32'h0
`define PROMPT_B          32'h0
`define PROMPT_C          32'h0
`define PROMPT_D          32'h0
`define PROMPT_E          32'h0
`define PROMPT_F          32'h0
`define PROMPT_G          32'h0
`define PROMPT_H          32'h0
`define PROMPT_I          32'h0
`define PROMPT_J          32'h0
`define PROMPT_K          32'h0
`define PROMPT_L          32'h0
`define PROMPT_M          32'h0
`define PROMPT_N          32'h0
`define PROMPT_O          32'h0
`define PROMPT_P          32'h0
`define PROMPT_Q          32'h0
`define PROMPT_R          32'h0
`define PROMPT_S          32'h0
`define PROMPT_T          32'h0
`define PROMPT_U          32'h0
`define PROMPT_V          32'h0
`define PROMPT_W          32'h0
`define PROMPT_X          32'h0
`define PROMPT_Y          32'h0
`define PROMPT_Z          32'h0

`define SEQMOD_A          32'h0
`define SEQMOD_B          32'h0
`define SEQMOD_C          32'h0
`define SEQMOD_D          32'h0
`define SEQMOD_E          32'h0
`define SEQMOD_F          32'h0
`define SEQMOD_G          32'h0
`define SEQMOD_H          32'h0
`define SEQMOD_I          32'h0
`define SEQMOD_J          32'h0
`define SEQMOD_K          32'h0
`define SEQMOD_L          32'h0
`define SEQMOD_M          32'h0
`define SEQMOD_N          32'h0
`define SEQMOD_O          32'h0
`define SEQMOD_P          32'h0
`define SEQMOD_Q          32'h0
`define SEQMOD_R          32'h0
`define SEQMOD_S          32'h0
`define SEQMOD_T          32'h0
`define SEQMOD_U          32'h0
`define SEQMOD_V          32'h0
`define SEQMOD_W          32'h0
`define SEQMOD_X          32'h0
`define SEQMOD_Y          32'h0
`define SEQMOD_Z          32'h0 */
